[32mINFO    [0m root:test_company_overview.py:77 test_time_series_daily_invalid_symbol started
[32mINFO    [0m root:test_company_overview.py:81 response : {
    "Error Message": "Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for OVERVIEW."
}
[32mINFO    [0m root:test_company_overview.py:86 test_time_series_daily_invalid_symbol ended